version: 2
updates:
- package-ecosystem: npm
  directory: "/twd3-web"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.9.1
  - dependency-name: "@quasar/app"
    versions:
    - 2.2.3
    - 2.2.4
  - dependency-name: "@quasar/extras"
    versions:
    - 1.10.0
    - 1.10.2
  - dependency-name: quasar
    versions:
    - 1.15.10
    - 1.15.7
    - 1.15.9
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.8.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: elliptic
    versions:
    - 6.5.4
